// Code generated by mockery v2.12.1. DO NOT EDIT.

package state

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

// GetFilter provides a mock function with given fields:
func (_m *MockObserver) GetFilter() map[string][]byte {
	ret := _m.Called()

	var r0 map[string][]byte
	if rf, ok := ret.Get(0).(func() map[string][]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *MockObserver) GetID() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Update provides a mock function with given fields: result
func (_m *MockObserver) Update(result *SubscriptionResult) {
	_m.Called(result)
}

// NewMockObserver creates a new instance of MockObserver. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockObserver(t testing.TB) *MockObserver {
	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
