// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"

	types "github.com/ChainSafe/gossamer/dot/types"
)

// BabeVerifier is an autogenerated mock type for the BabeVerifier type
type BabeVerifier struct {
	mock.Mock
}

// VerifyBlock provides a mock function with given fields: header
func (_m *BabeVerifier) VerifyBlock(header *types.Header) error {
	ret := _m.Called(header)

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Header) error); ok {
		r0 = rf(header)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBabeVerifier creates a new instance of BabeVerifier. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewBabeVerifier(t testing.TB) *BabeVerifier {
	mock := &BabeVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
